/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats { 'clipCount' : bigint, 'userCount' : bigint }
export type AspectRatio = { '_1_1' : null } |
  { '_16_9' : null } |
  { '_9_16' : null };
export type ExternalBlob = Uint8Array;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoClip {
  'id' : string,
  'startTime' : [] | [number],
  'title' : string,
  'endTime' : [] | [number],
  'partNumber' : [] | [bigint],
  'videoBlob' : [] | [ExternalBlob],
  'uploaderPrincipal' : Principal,
  'caption' : string,
  'videoUrl' : [] | [string],
  'uploadTime' : Time,
  'aspectRatio' : AspectRatio,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addVideoClip' : ActorMethod<
    [
      string,
      string,
      string,
      AspectRatio,
      [] | [bigint],
      [] | [ExternalBlob],
      [] | [string],
      [] | [number],
      [] | [number],
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteClip' : ActorMethod<[string], undefined>,
  'demoteFromAdmin' : ActorMethod<[Principal], undefined>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTotalClipsForUser' : ActorMethod<[Principal], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllUsers' : ActorMethod<[], Array<[Principal, UserRole]>>,
  'listClips' : ActorMethod<[], Array<VideoClip>>,
  'listMyClips' : ActorMethod<[], Array<VideoClip>>,
  'promoteToAdmin' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];