/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AspectRatio = IDL.Variant({
  '_1_1' : IDL.Null,
  '_16_9' : IDL.Null,
  '_9_16' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminStats = IDL.Record({
  'clipCount' : IDL.Nat,
  'userCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const VideoClip = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'partNumber' : IDL.Opt(IDL.Nat),
  'videoBlob' : IDL.Opt(ExternalBlob),
  'uploaderPrincipal' : IDL.Principal,
  'caption' : IDL.Text,
  'videoUrl' : IDL.Opt(IDL.Text),
  'uploadTime' : Time,
  'aspectRatio' : AspectRatio,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addVideoClip' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        AspectRatio,
        IDL.Opt(IDL.Nat),
        IDL.Opt(ExternalBlob),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteClip' : IDL.Func([IDL.Text], [], []),
  'demoteFromAdmin' : IDL.Func([IDL.Principal], [], []),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserRole))],
      ['query'],
    ),
  'listClips' : IDL.Func([], [IDL.Vec(VideoClip)], ['query']),
  'listMyClips' : IDL.Func([], [IDL.Vec(VideoClip)], ['query']),
  'promoteToAdmin' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AspectRatio = IDL.Variant({
    '_1_1' : IDL.Null,
    '_16_9' : IDL.Null,
    '_9_16' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminStats = IDL.Record({
    'clipCount' : IDL.Nat,
    'userCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const VideoClip = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'partNumber' : IDL.Opt(IDL.Nat),
    'videoBlob' : IDL.Opt(ExternalBlob),
    'uploaderPrincipal' : IDL.Principal,
    'caption' : IDL.Text,
    'videoUrl' : IDL.Opt(IDL.Text),
    'uploadTime' : Time,
    'aspectRatio' : AspectRatio,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addVideoClip' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          AspectRatio,
          IDL.Opt(IDL.Nat),
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteClip' : IDL.Func([IDL.Text], [], []),
    'demoteFromAdmin' : IDL.Func([IDL.Principal], [], []),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserRole))],
        ['query'],
      ),
    'listClips' : IDL.Func([], [IDL.Vec(VideoClip)], ['query']),
    'listMyClips' : IDL.Func([], [IDL.Vec(VideoClip)], ['query']),
    'promoteToAdmin' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };